# prueba  de botfront-stack
#
version: "3.8"

networks:
  private:
  proxy:
    external: true
    name: traefik-public
    
 
volumes:
  rasa_data:
  rasa_actions_data:
  db_data:
  filebrowser_data:

services:
  rasa:
    image: botfront/rasa-for-botfront:v2.3.3-bf.3
    deploy:
      placement:
        constraints:
          - node.role == worker
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.rasa_${NAME}-http.rule=Host(`socket.${NAME}.saia.ar`)
        - traefik.http.routers.rasa_${NAME}-http.entrypoints=http
        - traefik.http.routers.rasa_${NAME}-http.middlewares=https-redirect
        - traefik.http.routers.rasa_${NAME}-https.rule=Host(`socket.${NAME}.saia.ar`)
        - traefik.http.routers.rasa_${NAME}-https.entrypoints=https
        - traefik.http.routers.rasa_${NAME}-https.tls=true
        - traefik.http.routers.rasa_${NAME}-https.tls.certresolver=le
        - traefik.http.services.rasa_${NAME}.loadbalancer.server.port=5005
    networks:
      - private
      - proxy
    volumes:
      - rasa_data:/app/models
    environment:
      - BF_PROJECT_ID=${BF_PROJECT_ID-X5oK2rmS2GZTQ87Lk}
      - BF_URL=http://botfront:3000/graphql
      - AUGMENTATION_FACTOR=50
      - MONGO_URL=mongodb://mongo:27017/bf
      
  botfront:
    image: botfront/botfront:v1.0.6-patch.1
    
    deploy:
      placement:
        constraints:
          - node.role == worker
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.${NAME}-http.rule=Host(`botfront.${NAME}.saia.ar`)
        - traefik.http.routers.${NAME}-http.entrypoints=http
        - traefik.http.routers.${NAME}-http.middlewares=https-redirect
        - traefik.http.routers.${NAME}-https.rule=Host(`botfront.${NAME}.saia.ar`)
        - traefik.http.routers.${NAME}-https.entrypoints=https
        - traefik.http.routers.${NAME}-https.tls=true
        - traefik.http.routers.${NAME}-https.tls.certresolver=le
        - traefik.http.services.${NAME}.loadbalancer.server.port=3000
    networks:
      - private
      - proxy
    #ports:
     # - "${CODE-400}00:3000"
    volumes:
      - rasa_data:/app/models:ro
    environment:
      - PORT=3000
      - ROOT_URL=https://botfront.${NAME}.saia.ar
      - AUGMENTATION_FACTOR=50
      - MONGO_URL=mongodb://mongo:27017/bf
      
  actions:
    image: rasa/rasa-sdk:2.1.2
    deploy:
      placement:
        constraints:
          - node.role == worker
    networks:
      - private
    volumes:
      - rasa_actions_data:/app/actions
    command:
      - start
      - --debug
      - --actions
      - actions
    environment:
      - BF_PROJECT_ID=${BF_PROJECT_ID-X5oK2rmS2GZTQ87Lk}
      
  duckling:

    image: botfront/duckling
    deploy:
      placement:
        constraints:
          - node.role == worker
    networks:
      - private
     
  mongo:
    image: mongo
    deploy:
      placement:
        constraints:
          - node.role == worker
    networks:
      - private
    volumes:
      - db_data:/data/db
    environment:
      - BF_PROJECT_ID=${BF_PROJECT_ID-X5oK2rmS2GZTQ87Lk}
      - BF_URL=http://botfront:3000/graphql
      - AUGMENTATION_FACTOR=50
      - MONGO_URL=mongodb://mongo:27017/bf
      


